### ISSUE TITLE
Strange Characters in saved settings.json leads to failed loading

### ISSUE THREAD

**Issue by alexJaegerSTR** [intersystems-ru/Cache-MDX2JSON#63] opened 2017-03-03 16:13 UTC
When saved, our json contains a lot of wrongly encoded (and duplicated) characters
in any placer where we used a non ascii Dashboard or pivot name. 

Trying to load such a config fails to parse and does require manually editing the respective MDX2JSON Global in Caché to restore the settings.

Example (the correct name should have been Dashboards/Übersicht:
`Dashboards/ÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃ
ÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂbersicht `

**Comment by eduard93** [comment] 2017-03-03 17:53
Please provide output from `/MDX2JSON/Test?Debug`

**Comment by eduard93** [comment] 2017-03-03 17:54
Also pinging @gnibeda

**Comment by alexJaegerSTR** [comment] 2017-03-06 10:13
Hi @eduard93  thanks for your reply.

Test?Debug shwos
`
{
    "Cache":"Cache for Windows (x86-64) 2016.2.1 (Build 803U) Wed Oct 26 2016 12:31:28 EDT",
    "DefaultApp":"\/dsw",
    "Mappings": {
        "Mapped":["%SYS","ENSDEMO","ENSEMBLE","COMPANY_NAME","MDX2JSON","SAMPLES","USER","WEBTEST"
        ],
        "Unmapped":["DOCBOOK"
        ]
    },
    "Namespace":"MDX2JSON",
    "Parent":"e5c7ec2bf606b6e7fafede1472014829b854acf5",
    "ParentTS":"2017-02-10 14:31:42.032",
    "Request": {
        "URL":"\/mdx2json\/Test",
        "PageName":"Test",
        "URLPrefix":"",
        "UserAgent":"Mozilla\/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/56.0.2924.87 Safari\/537.36",
        "RequestId":"20B",
        "ContentType":"",
        "CharSet":"",
        "Content":"",
        "Method":"GET",
        "Protocol":"HTTP\/1.1",
        "Secure":false,
        "GatewayApplication":"\/",
        "GatewayConnectionName":"LOCAL",
        "GatewaySessionIdSource":3,
        "GatewayNewId":false,
        "GatewayBuild":"661.1602.1573d",
        "GatewayFunctions":"7",
        "GatewaySessionCookie":"CSPSESSIONID-SP-57772-UP-mdx2json-",
        "GatewayInstanceName":"PC0868:57772",
        "GatewayError":"",
        "Application":"\/mdx2json\/",
        "CSPGatewayRequest":true,
        "GatewayTimeout":60,
        "AppData":"",
        "AppMatch":"\/mdx2json\/",
        "Class":"MDX2JSON.REST",
        "Service":"REST",
        "ProcessedRequestType":true
    },
    "Response": {
        "HTTPVersion":"",
        "Status":"200 OK",
        "Redirect":"",
        "ServerSideRedirect":"",
        "ContentType":"application\/json",
        "CharSet":"utf-8",
        "CookiePath":"\/mdx2json\/",
        "HeaderCharSet":"",
        "ContentLength":"",
        "NoCharSetConvert":false,
        "UseHttpOnly":true,
        "InProgress":1,
        "Expires":"Thu, 29 Oct 1998 17:04:19 GMT",
        "VaryByParam":"",
        "TraceDump":false,
        "OutputSessionToken":true,
        "UseASPredirect":false,
        "Timeout":"",
        "Language":"de",
        "Domain":"",
        "GzipOutput":null,
        "AvoidPartitionCleanup":false
    },
    "Roles":"%All",
    "SessionId":"afmRoglA4l",
    "Status":"OK",
    "User":"UnknownUser",
    "Version":2.2
}
`

We suspect an encoding problem (the names were entered in the DeepSee user portal and our Caché Database is encoded in German-3)

**Comment by eduard93** [comment] 2017-03-10 08:18
Hello.
I have done the following steps to reproduce your issue.

1. Created a new namespace, `UBER`.
2. Created a new dashboard there (left title empty), named `Dashboards/Übersicht`.
3. Added a new widget to dashboard and saved it.
4. Opened  `Dashboards/Übersicht` in DSW and resized the dashboard.
5. Saved DSW settings.
6. Loaded DSW settings.
7. Dashboard was displayed correctly in DSW.

Here's my ^MDX2JSON("Settings","Admin","UBER") global value:
```
"{""Default"":{""app"":{""language"":""en"",""hideFolders"":false,""showImages"":false,""theme"":""themes/contrast.css"",""isSaveFilters"":true},""namespaces"":{""widgets"":{""Dashboards/Übersicht.dashboard"":{""Widget1"":{""sizeX"":8,""sizeY"":10}}}}}}"
```

And here's result of a call to `http://host/MDX2JSON/Config/UBER`:
```
{
   "Config":"{\"Default\":{\"app\":{\"language\":\"en\",\"hideFolders\":false,\"showImages\":false,\"theme\":\"themes\/contrast.css\",\"isSaveFilters\":true},\"namespaces\":{\"widgets\":{\"Dashboards\/Übersicht.dashboard\":{\"Widget1\":{\"sizeX\":8,\"sizeY\":10}}}}}}"
}
```

So, I'm unable to reproduce the issue.
Do you have any suggestions on how to reproduce the issue?

**Comment by alexJaegerSTR** [comment] 2017-03-10 09:37
Hi Eduard,

the save and loading functions are working fine, however when exporting the settings to JSON and loading it back in again (or into another instance of caché) it produces the incorrectly encoded characters in the global.

so our workflow was:

1. Create a new workspace and store settings as you did
2. "Export Setting" to JSON (looks good)
{"ns":{"tiles":{"":{"":{"row":0,"col":0,"sizeX":1,"sizeY":1,"color":2,"fontColor":0,"icon":27,"title":""},"Übersicht":{"row":0,"col":1,"sizeX":9,"sizeY":2,"color":1,"fontColor":0,"icon":1,"title":"Übersicht"}},"Dashboard/":{"":{"row":0,"col":0,"sizeX":1,"sizeY":1,"color":2,"fontColor":0,"icon":27,"title":""},"Übersicht":{"row":0,"col":1,"sizeX":10,"sizeY":3,"color":1,"fontColor":0,"icon":1,"title":"Übersicht"}}}}}

3. "Import Settings" 
(now the global contains)

^MDX2JSON("Settings","UnknownUser","UBER")	=	{"Default":{"app":{"language":"en","hideFolders":false,"showImages":false,"theme":"","isSaveFilters":true},"namespaces":{"tiles":{"":{"":{"row":0,"col":0,"sizeX":1,"sizeY":1,"color":2,"fontColor":0,"icon":27,"title":""},"Ãbersicht":{"row":0,"col":1,"sizeX":9,"sizeY":2,"color":1,"fontColor":0,"icon":1,"title":"Ãbersicht"}},"Dashboard/":{"":{"row":0,"col":0,"sizeX":1,"sizeY":1,"color":2,"fontColor":0,"icon":27,"title":""},"Ãbersicht":{"row":0,"col":1,"sizeX":10,"sizeY":3,"color":1,"fontColor":0,"icon":1,"title":"Ãbersicht"}}}}}}

4. "Export again" to JSON

{"ns":{"tiles":{"":{"":{"row":0,"col":0,"sizeX":1,"sizeY":1,"color":2,"fontColor":0,"icon":27,"title":""},"Ãbersicht":{"row":0,"col":1,"sizeX":9,"sizeY":2,"color":1,"fontColor":0,"icon":1,"title":"Ãbersicht"}},"Dashboard/":{"":{"row":0,"col":0,"sizeX":1,"sizeY":1,"color":2,"fontColor":0,"icon":27,"title":""},"Ãbersicht":{"row":0,"col":1,"sizeX":10,"sizeY":3,"color":1,"fontColor":0,"icon":1,"title":"Ãbersicht"}}}}}

For me this looks like the error occurs when importing the settings back from the loaded file. If you need anything else, I'm happy to help

**Comment by eduard93** [comment] 2017-03-10 17:09
Method "Import Settings" does not work for me in ff and chrome.
Maybe related to https://github.com/intersystems-ru/DeepSeeWeb/issues/38

**Comment by gnibeda** [comment] 2017-04-18 14:34
@eduard93 issue with import/export settings was fixed in [2.0.26](https://github.com/intersystems-ru/DeepSeeWeb/releases/tag/2.0.26)

**Comment by eduard93** [comment] 2017-04-18 16:49
@gnibeda does it fix this issue?

**Comment by eduard93** [comment] 2017-04-20 15:25
@gnibeda Chrome shows some bad characters in request
![default](https://cloud.githubusercontent.com/assets/5127457/25238616/9172d152-25f6-11e7-99f9-2e5173c80081.PNG)


Temp fix:
 add `set config = $zcvt(config, "I", "UTF8")` before `return` in `MDX2JSON.REST:SetConfig`

**Closed** 2019-07-23 12:11 UTC
